### ISSUE TITLE
nie dziala na linux

### ISSUE THREAD

**Issue by Mefizo** [neziw/Hello-World#5]
nie dziala na linux

**Comment by neziw** [comment]
@Mefizo trochę nie rozumiem co ma tutaj nie działać. To są zwykłe sample z bardziej znanych języków programowania na pierwszy program, który się pisze na początku nauki bądź testów instalacji. 

Jeżeli chodzi o Assemblera to nie pamiętam pod jaki konkretnie procesor i architekturę jest kod więc nie pomogę.
